$ErrorActionPreference = 'Stop'

$architectureDir = 'docs/architecture'
$indexPath = Join-Path $architectureDir 'index.md'

if (-not (Test-Path $architectureDir)) {
    New-Item -ItemType Directory -Path $architectureDir -Force | Out-Null
}

$files = Get-ChildItem -Path $architectureDir -File -Filter '*.md' |
    Where-Object { $_.Name -ne 'index.md' } |
    Sort-Object Name

# Also collect architecture-prefixed docs from the parent docs/ directory
$parentArchFiles = Get-ChildItem -Path 'docs' -File -Filter '*.md' |
    Where-Object { $_.Name -match '^architecture-' -or $_.Name -eq 'integration-architecture.md' } |
    Sort-Object Name

$lines = @()
$lines += '# Architecture Index'
$lines += ''
$lines += 'Generated by `.github/scripts/generate-architecture-index.ps1`.'
$lines += ''

$totalCount = $files.Count + $parentArchFiles.Count

if ($totalCount -eq 0) {
    $lines += '- _No architecture markdown documents found._'
}
else {
    foreach ($file in $files) {
        $lines += "- [$($file.Name)]($($file.Name))"
    }
    foreach ($file in $parentArchFiles) {
        $lines += "- [$($file.Name)](../$($file.Name))"
    }
}

$lines += ''

Set-Content -Path $indexPath -Value $lines -Encoding UTF8
Write-Host "Wrote architecture index to $indexPath"
