$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$architectureDir = 'docs/architecture'
$indexPath = Join-Path $architectureDir 'index.md'
$docsRoot = 'docs'

if (-not (Test-Path $architectureDir)) {
    New-Item -ItemType Directory -Path $architectureDir -Force | Out-Null
}

function Get-DocumentTitle {
    param(
        [System.IO.FileInfo]$File
    )

    $heading = Get-Content -Path $File.FullName -TotalCount 40 |
    Where-Object { $_ -match '^#\s+.+$' } |
    Select-Object -First 1

    if ($heading) {
        return ($heading -replace '^#\s+', '').Trim()
    }

    return $File.BaseName
}

function Get-RelativeLinkPath {
    param(
        [string]$FromDirectory,
        [string]$ToFilePath
    )

    $fromResolved = (Resolve-Path $FromDirectory).Path
    $toResolved = (Resolve-Path $ToFilePath).Path

    $fromUri = [System.Uri]::new(($fromResolved.TrimEnd([char[]]@('/', '\')) + [System.IO.Path]::DirectorySeparatorChar))
    $toUri = [System.Uri]::new($toResolved)

    return [System.Uri]::UnescapeDataString($fromUri.MakeRelativeUri($toUri).ToString())
}

$localArchitectureDocs = @(
    Get-ChildItem -Path $architectureDir -File -Filter '*.md' |
    Where-Object { $_.Name -ne 'index.md' } |
    Sort-Object FullName
)

$crossCuttingDocs = @(
    Get-ChildItem -Path $docsRoot -File -Filter '*.md' |
    Where-Object {
        $_.FullName -notlike "*$architectureDir*" -and
        $_.Name -imatch 'architecture'
    } |
    Sort-Object FullName
)

$lines = @()
$lines += '# Architecture Index'
$lines += ''
$lines += 'Generated by `.github/scripts/generate-architecture-index.ps1`.'
$lines += ''

$hasAnyDocs = ($localArchitectureDocs.Count -gt 0) -or ($crossCuttingDocs.Count -gt 0)

if (-not $hasAnyDocs) {
    $lines += '- _No architecture markdown documents found._'
}
else {
    $lines += '## docs/architecture/'
    if ($localArchitectureDocs.Count -eq 0) {
        $lines += '- _No architecture markdown documents found in this directory._'
    }
    else {
        foreach ($file in $localArchitectureDocs) {
            $title = Get-DocumentTitle -File $file
            $link = Get-RelativeLinkPath -FromDirectory $architectureDir -ToFilePath $file.FullName
            $lines += "- [$title]($link)"
        }
    }

    if ($crossCuttingDocs.Count -gt 0) {
        $lines += ''
        $lines += '## Top-level architecture docs'
        foreach ($file in $crossCuttingDocs) {
            $title = Get-DocumentTitle -File $file
            $link = Get-RelativeLinkPath -FromDirectory $architectureDir -ToFilePath $file.FullName
            $lines += "- [$title]($link)"
        }
    }
}

$lines += ''

Set-Content -Path $indexPath -Value $lines -Encoding UTF8
Write-Host "Wrote architecture index to $indexPath"
